# Assignment 1 numpy class 1

## 1.shape of NumPy array

In [3]:
import numpy as np
 
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 
print(array1d.shape)
print(array2d.shape)
print(array3d.shape)

(6,)
(2, 3)
(2, 2, 3)


## 2. 1, 2 or 3 dimension NumPy array

In [5]:
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d.ndim)  # 1
 
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d.ndim)  # 2
 
array3d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array3d = array3d.reshape(2, 3, 2)
print(array3d.ndim)

1
2
3


## 3.resize NumPy array

In [6]:
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)

[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


## 4. reshape NumPy array

In [8]:
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray = thearray.reshape(2, 4)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(4, 2)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(8, 1)
print(thearray)


[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## 5.convert List or Tuple into NumPy array

In [9]:
thelist = [1, 2, 3]
print(type(thelist))  # <class 'list'>
 
array1 = np.array(thelist)
print(type(array1))  # <class 'numpy.ndarray'>
 
 
thetuple = ((1, 2, 3))
print(type(thetuple))  # <class 'tuple'>
 
array2 = np.array(thetuple)
print(type(array2))  # <class 'numpy.ndarray'>
 
array3 = np.array([thetuple, thelist, array1])
print(array3)

<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]]


## 6.NumPy array using arange function

In [10]:
array1d = np.arange(5)  # 1 row and 5 columns
print(array1d)
 
array1d = np.arange(0, 12, 2)  # 1 row and 6 columns
print(array1d)
 
array2d = np.arange(0, 12, 2).reshape(2, 3)  # 2 rows 3 columns
print(array2d)
 
array3d = np.arange(9).reshape(3, 3)  # 3 rows and columns
print(array3d)

[0 1 2 3 4]
[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


 ##  7.NumPy arrays with linspace()

In [11]:
array1d = np.linspace(1, 12, 2)
print(array1d)
 
array1d = np.linspace(1, 12, 4)
print(array1d)
 
array2d = np.linspace(1, 12, 12).reshape(4, 3)
print(array2d)

[ 1. 12.]
[ 1.          4.66666667  8.33333333 12.        ]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


## 8. NumPy logspace array

In [12]:
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)

[1.00000000e+35 7.74263683e+38 5.99484250e+42 4.64158883e+46
 3.59381366e+50 2.78255940e+54 2.15443469e+58 1.66810054e+62
 1.29154967e+66 1.00000000e+70]


## 9. NumPy logspace array

In [13]:
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)

[1.00000000e+35 7.74263683e+38 5.99484250e+42 4.64158883e+46
 3.59381366e+50 2.78255940e+54 2.15443469e+58 1.66810054e+62
 1.29154967e+66 1.00000000e+70]


## 10. create Zeros NumPy arrays

In [14]:
array1d = np.zeros(3)
print(array1d)
 
array2d = np.zeros((2, 4))
print(array2d)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 11. NumPy One array

In [15]:
array1d = np.ones(3)
print(array1d)
 
array2d = np.ones((2, 4))
print(array2d)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12. NumPy Full array

In [16]:
array1d = np.full((3), 2)
print(array1d)
 
array2d = np.full((2, 4), 3)
print(array2d)

[2 2 2]
[[3 3 3 3]
 [3 3 3 3]]


## 13. NumPy Eye array

In [17]:
array1 = np.eye(3, dtype=int)
print(array1)
 
array2 = np.eye(5, k=2)
print(array2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 14. NumPy generate random number 

In [18]:
print(np.random.rand(3, 2))  # Uniformly distributed values.
print(np.random.randn(3, 2))  # Normally distributed values.
 
# Uniformly distributed integers in a given range.
print(np.random.randint(2, size=10))
print(np.random.randint(5, size=(2, 4)))

[[0.99611961 0.46905527]
 [0.2278019  0.48736216]
 [0.48523451 0.51889624]]
[[-0.61702661 -0.47782216]
 [-0.30373218  0.79863489]
 [ 0.11866061  0.92976535]]
[0 1 1 1 0 1 0 1 0 0]
[[2 3 2 2]
 [0 3 2 4]]


## 15. NumPy Identity and Diagonal Array

In [19]:

print(np.identity(3))
 
print(np.diag(np.arange(0, 8, 2)))
 
print(np.diag(np.diag(np.arange(9).reshape((3,3)))))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]
[[0 0 0]
 [0 4 0]
 [0 0 8]]


## 16.NumPy Indexing

In [20]:
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d[0])   # Get first value
print(array1d[-1])  # Get last value
print(array1d[3])   # Get 4th value from first
print(array1d[-5])  # Get 5th value from last
 
# Get multiple values
print(array1d[[0, -1]])
 
print("-" * 10)
 
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)
print("-" * 10)
 
print(array2d[0, 0])   # Get first row first col
print(array2d[0, 1])   # Get first row second col
print(array2d[0, 2])   # Get first row third col
 
print(array2d[0, 1])   # Get first row second col 
print(array2d[1, 1])   # Get second row second col
print(array2d[2, 1])   # Get third row second col

1
6
4
2
[1 6]
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
1
2
3
2
5
8


## 17. NumPy Indexing in Multidimensional

In [21]:
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3d)
 
print(array3d[0, 0, 0])
print(array3d[0, 0, 1])
print(array3d[0, 0, 2])
 
print(array3d[0, 1, 0])
print(array3d[0, 1, 1])
print(array3d[0, 1, 2])
 
print(array3d[1, 0, 0])
print(array3d[1, 0, 1])
print(array3d[1, 0, 2])
 
print(array3d[1, 1, 0])
print(array3d[1, 1, 1])
print(array3d[1, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


## 18. NumPy Single Dimensional Slicing

In [22]:
array1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
print(array1d[4:])  # From index 4 to last index
 
print(array1d[:4])  # From index 0 to 4 index
 
print(array1d[4:7])  # From index 4(included) up to index 7(excluded)
 
print(array1d[:-1])  # Excluded last element
 
print(array1d[:-2])  # Up to second last index(negative index)
 
print(array1d[::-1])  # From last to first in reverse order(negative step)
 
print(array1d[::-2])  # All odd numbers in reversed order
 
print(array1d[-2::-2])  # All even numbers in reversed order
 
print(array1d[::])  # All elements

[4 5 6 7 8 9]
[0 1 2 3]
[4 5 6]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]
[8 6 4 2 0]
[0 1 2 3 4 5 6 7 8 9]


## 19. Multidimensional Slicing in NumPy Array

In [23]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
print("-" * 10)
print(array2d[:, 0:2])  # 2nd and 3rd col
 
print("-" * 10)
print(array2d[1:3, 0:3])  # 2nd and 3rd row
 
print("-" * 10)
print(array2d[-1::-1, -1::-1])  # Reverse an array

----------
[[1 2]
 [4 5]
 [7 8]]
----------
[[4 5 6]
 [7 8 9]]
----------
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 20. Flips the order of the axes of an NumPy Array

In [24]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)
 
print("-" * 10)
 
# Permute the dimensions of an array.
arrayT = np.transpose(array2d)
print(arrayT)
 
print("-" * 10)
 
# Flip array in the left/right direction.
arrayFlr = np.fliplr(array2d)
print(arrayFlr)
 
print("-" * 10)
 
# Flip array in the up/down direction.
arrayFud = np.flipud(array2d)
print(arrayFud)
 
print("-" * 10)
 
# Rotate an array by 90 degrees in the plane specified by axes.
arrayRot90 = np.rot90(array2d)
print(arrayRot90)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 4 7]
 [2 5 8]
 [3 6 9]]
----------
[[3 2 1]
 [6 5 4]
 [9 8 7]]
----------
[[7 8 9]
 [4 5 6]
 [1 2 3]]
----------
[[3 6 9]
 [2 5 8]
 [1 4 7]]


## 21. Joining and Stacking of NumPy arrays

In [25]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
# Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)
 
print("-" * 10)
 
# Stack arrays in sequence vertically (row wise).
arrayV = np.vstack((array1, array2))
print(arrayV)
 
print("-" * 10)
 
# Stack arrays in sequence depth wise (along third axis).
arrayD = np.dstack((array1, array2))
print(arrayD)
 
print("-" * 10)
 
# Appending arrays after each other, along a given axis.
arrayC = np.concatenate((array1, array2))
print(arrayC)
 
print("-" * 10)
 
# Append values to the end of an array.
arrayA = np.append(array1, array2, axis=0)
print(arrayA)
 
print("-" * 10)
arrayA = np.append(array1, array2, axis=1)
print(arrayA)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 22. Arithmetic Operations with NumPy Array

In [26]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
print(array1 + array2)
print("-" * 20)
 
print(array1 - array2)
print("-" * 20)
 
print(array1 * array2)
print("-" * 20)
 
print(array2 / array1)
print("-" * 40)
 
print(array1 ** array2)
print("-" * 40)

[[ 8 10 12]
 [14 16 18]]
--------------------
[[-6 -6 -6]
 [-6 -6 -6]]
--------------------
[[ 7 16 27]
 [40 55 72]]
--------------------
[[7.  4.  3. ]
 [2.5 2.2 2. ]]
----------------------------------------
[[          1         256       19683]
 [    1048576    48828125 -2118184960]]
----------------------------------------


## 23. Scalar Arithmetic Operations on NumPy Array

In [28]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(array1 + 2)
print("-" * 20)
 
print(array1 - 5)
print("-" * 20)
 
print(array1 * 2)
print("-" * 20)
 
print(array1 / 5)
print("-" * 20)
 
print(array1 ** 2)
print("-" * 20)

[[12 22 32]
 [42 52 62]]
--------------------
[[ 5 15 25]
 [35 45 55]]
--------------------
[[ 20  40  60]
 [ 80 100 120]]
--------------------
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
--------------------
[[ 100  400  900]
 [1600 2500 3600]]
--------------------


## 24. NumPy Elementary Mathematical Functions

In [29]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(np.sin(array1))
print("-" * 40)
 
print(np.cos(array1))
print("-" * 40)
 
print(np.tan(array1))
print("-" * 40)
 
print(np.sqrt(array1))
print("-" * 40)
 
print(np.exp(array1))
print("-" * 40)
 
print(np.log10(array1))
print("-" * 40)

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]
----------------------------------------
[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]
----------------------------------------
[[ 0.64836083  2.23716094 -6.4053312 ]
 [-1.11721493 -0.27190061  0.32004039]]
----------------------------------------
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
----------------------------------------
[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]
----------------------------------------
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
----------------------------------------


## 25. NumPy Element Wise Mathematical Operations

In [30]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[2, 3, 4], [4, 6, 8]])
array3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])
 
print(np.add(array1, array2))
print("-" * 40)
 
print(np.power(array1, array2))
print("-" * 40)
 
print(np.remainder((array2), 5))
print("-" * 40)
 
print(np.reciprocal(array3))
print("-" * 40)
 
print(np.sign(array3))
print("-" * 40)
 
print(np.ceil(array3))
print("-" * 40)
 
print(np.round(array3))
print("-" * 40)

[[12 23 34]
 [44 56 68]]
----------------------------------------
[[        100        8000      810000]
 [    2560000 -1554869184 -1686044672]]
----------------------------------------
[[2 3 4]
 [4 1 3]]
----------------------------------------
[[-0.5         0.28571429 -0.25      ]
 [ 0.24691358 -0.16666667  0.125     ]]
----------------------------------------
[[-1.  1. -1.]
 [ 1. -1.  1.]]
----------------------------------------
[[-2.  4. -4.]
 [ 5. -6.  8.]]
----------------------------------------
[[-2.  4. -4.]
 [ 4. -6.  8.]]
----------------------------------------


## 26. NumPy Aggregate and Statistical Functions

In [31]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print("Mean: ", np.mean(array1))
 
print("Std: ", np.std(array1))
 
print("Var: ", np.var(array1))
 
print("Sum: ", np.sum(array1))
 
print("Prod: ", np.prod(array1))

Mean:  35.0
Std:  17.07825127659933
Var:  291.6666666666667
Sum:  210
Prod:  720000000


## 27.NumPy Example of Where function

In [32]:
 
before = np.array([[1, 2, 3], [4, 5, 6]])
 
# If element is less than 4, mul by 2 else by 3
after = np.where(before < 4, before * 2, before * 3)
 
print(after)

[[ 2  4  6]
 [12 15 18]]


## 28. NumPy Example of Select function

In [33]:
before = np.array([[1, 2, 3], [4, 5, 6]])
 
# If element is less than 4, mul by 2 else by 3
after = np.select([before < 4, before], [before * 2, before * 3])
 
print(after)

[[ 2  4  6]
 [12 15 18]]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: select condlists containing integer ndarrays is deprecated and will be removed in the future. Use `.astype(bool)` to convert to bools.
  after removing the cwd from sys.path.


## 29.NumPy Example of Choose function

In [35]:
before = np.array([[0, 1, 2], [2, 0, 1], [1, 2, 0]])
choices = [5, 10, 15]
 
after = np.choose(before, choices)
print(after)
 
print("-" * 10)
 
before = np.array([[0, 0, 0], [2, 2, 2], [1, 1, 1]])
choice1 = [5, 10, 15]
choice2 = [8, 16, 24]
choice3 = [9, 18, 27]
 
after = np.choose(before, (choice1, choice2, choice3))
print(after)

[[ 5 10 15]
 [15  5 10]
 [10 15  5]]
----------
[[ 5 10 15]
 [ 9 18 27]
 [ 8 16 24]]


## 30.NumPy Logical operations for selectively picking values from an array depending on a given condition

In [36]:
thearray = np.array([[10, 20, 30], [14, 24, 36]])
 
print(np.logical_or(thearray < 10, thearray > 15))
print("-" * 30)
 
print(np.logical_and(thearray < 10, thearray > 15))
print("-" * 30)
 
print(np.logical_not(thearray < 20))
print("-" * 30)

[[False  True  True]
 [False  True  True]]
------------------------------
[[False False False]
 [False False False]]
------------------------------
[[False  True  True]
 [False  True  True]]
------------------------------


## 31. NumPy example of Standard Set Operations

In [37]:
import numpy as np
 
array1 = np.array([[10, 20, 30], [14, 24, 36]])
array2 = np.array([[20, 40, 50], [24, 34, 46]])
 
# Find the union of two arrays.
print(np.union1d(array1, array2))
 
# Find the intersection of two arrays.
print(np.intersect1d(array1, array2))
 
# Find the set difference of two arrays.
print(np.setdiff1d(array1, array2))

[10 14 20 24 30 34 36 40 46 50]
[20 24]
[10 14 30 36]


## 32. Broadcasting

In [38]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## 33

In [39]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## 34

In [40]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## 35

In [41]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


## 36. Array math

In [42]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


## 37. 

In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## 38.

In [44]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


## 39.

In [45]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## 40. Data types

In [46]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


## 42. Array indexing

In [47]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


## 43

In [48]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


## 44

In [49]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


## 45

In [50]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## 46

In [51]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## 47. Splitting of arrays

In [52]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


## 48

In [53]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 49

In [54]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## 50

In [55]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
